### ISSUE TITLE
Test milestone regex

### ISSUE THREAD

**Issue by Sparragus** [Sparragus/test-github-api#1]
## Description
This issue will help with testing issues with a milestone title that matches against a giver regular expression.

## Adword
```yaml
name: Richard Kaufdman
url: https://twitter.com/sparragus
pic: https://avatars3.githubusercontent.com/u/80982
bio: Eventloop organizer
```
